test("test", () => {
  throw new Error("test failed");
});
